import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  console.log("🚀 ~ file: index.js:9 ~ Home ~ results", results);

  return (
    <>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <Header />

      {/* NAV */}
      <Nav />

      {/* Results */}
      <Results movies={results} />
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const req = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  )
    .then((res) => res.json())
    .then((data) => data.results);

  return {
    props: {
      results: req,
    },
  };
}
